{
 "title": "risingwave_dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "compute_node",
    "label": "compute_node",
    "query": {
     "query": "label_values(state_store_get_counts, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "sst count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(storage_level_sst_num{level_index=~\"L0|L1\"}[$__interval])"
    }
   ]
  },
  {
   "title": "compaction count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "storage_level_compact_frequency"
    }
   ]
  },
  {
   "title": "compacting sst count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "storage_level_compact_cnt" }
   ]
  },
  {
   "title": "GBs read from current level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "storage_level_compact_read_curr"
    }
   ]
  },
  {
   "title": "GBs read from next level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "storage_level_compact_read_next"
    }
   ]
  },
  {
   "title": "GBs written to next level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "storage_level_compact_write" }
   ]
  },
  {
   "title": "count of sst read from current level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "storage_level_compact_read_sstn_curr"
    }
   ]
  },
  {
   "title": "count of sst read from next level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "storage_level_compact_read_sstn_next"
    }
   ]
  },
  {
   "title": "count of sst written to next level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "storage_level_compact_write_sstn"
    }
   ]
  },
  { "title": "Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "barrier latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_p99"
    },
    {
     "expr": "irate(meta_barrier_duration_seconds_sum[1m]) / irate(meta_barrier_duration_seconds_count[1m])",
     "legendFormat": "barrier_latency_avg"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_p999"
    }
   ]
  },
  {
   "title": "actor throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(stream_actor_row_count[15s])",
     "legendFormat": "actor_id = {{actor_id}}"
    }
   ]
  },
  {
   "title": "source throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "rows/s" }
   ],
   "targets": [
    {
     "expr": "irate(stream_source_output_rows_counts[15s])",
     "legendFormat": "source_id = {{source_id}}"
    }
   ]
  },
  { "title": "Hummock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "read ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_get_duration_count[1m])) by (instance)",
     "legendFormat": "get (cn:{{instance}})"
    },
    {
     "expr": "sum(rate(state_store_range_scan_duration_count[1m])) by (instance)",
     "legendFormat": "range_scan (cn:{{instance}})"
    },
    {
     "expr": "sum(rate(state_store_range_reverse_scan_duration_count[1m])) by (instance)",
     "legendFormat": "reverse_range_scan (cn:{{instance}})"
    },
    {
     "expr": "sum(rate(state_store_get_shared_buffer_hit_counts[1m])) by (instance)",
     "legendFormat": "shared_buffer hit (cn:{{instance}})"
    }
   ]
  },
  {
   "title": "block ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_sst_store_block_request_counts[1m])) by (instance)",
     "legendFormat": "get (cn:{{instance}})"
    },
    {
     "expr": "sum(rate(state_store_sst_store_get_remote_duration_count[1m])) by (instance)",
     "legendFormat": "get remote (cn:{{instance}})"
    },
    {
     "expr": "sum(rate(state_store_sst_store_put_remote_duration_count[1m])) by (instance)",
     "legendFormat": "put remote (cn:{{instance}})"
    }
   ]
  },
  {
   "title": "read duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, instance)(rate(state_store_get_duration_sum[1m])) / sum by(le, instance) (rate(state_store_get_duration_count[1m]))",
     "legendFormat": "get avg (cn: {{instance}})"
    },
    {
     "expr": "sum by(le, instance)(rate(state_store_range_scan_duration_sum[1m])) / sum by(le, instance) (rate(state_store_range_scan_duration_count[1m]))",
     "legendFormat": "range_scan avg (cn: {{instance}})"
    },
    {
     "expr": "sum by(le, instance)(rate(state_store_range_reverse_scan_duration_sum[1m])) / sum by(le, instance) (rate(state_store_range_reverse_scan_duration_count[1m]))",
     "legendFormat": "reverse_range_scan avg (cn: {{instance}})"
    }
   ]
  },
  {
   "title": "sst read counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_bloom_filter_true_negative_counts[1m])) by (instance)",
     "legendFormat": "bloom filter true negative (cn:{{instance}})"
    },
    {
     "expr": "sum(rate(state_store_bloom_filter_might_positive_counts[1m])) by (instance)",
     "legendFormat": "bloom filter might positive (cn:{{instance}})"
    },
    {
     "expr": "sum by(le, instance)(rate(state_store_iter_merge_sstable_counts_sum[1m]))  / sum by(le, instance)(rate(state_store_iter_merge_sstable_counts_count[1m]))",
     "legendFormat": "# merged ssts avg (cn:{{instance}})"
    }
   ]
  },
  {
   "title": "sst store remote io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, instance)(rate(state_store_sst_store_get_remote_duration_sum[1m])) / sum by(le, instance) (rate(state_store_sst_store_get_remote_duration_count[1m]))",
     "legendFormat": "get block avg (cn: {{instance}})"
    },
    {
     "expr": "sum by(le, instance)(rate(state_store_sst_store_put_remote_duration_sum[1m])) / sum by(le, instance) (rate(state_store_sst_store_put_remote_duration_count[1m]))",
     "legendFormat": "put sst avg (cn: {{instance}})"
    }
   ]
  },
  {
   "title": "read throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance)(rate(state_store_get_key_size_sum[1m])+rate(state_store_get_value_size_sum[1m]))/sum by(instance)(rate(state_store_get_key_size_count[1m]))",
     "legendFormat": "get (cn:{{instance}})"
    },
    {
     "expr": "sum by(instance)(rate(state_store_get_key_size_sum[1m]))/sum by(instance)(rate(state_store_get_key_size_count[1m]))",
     "legendFormat": "get key (cn:{{instance}})"
    },
    {
     "expr": "sum by(instance)(rate(state_store_get_value_size_sum[1m]))/sum by(instance)(rate(state_store_get_value_size_count[1m]))",
     "legendFormat": "get value (cn:{{instance}})"
    },
    {
     "expr": "sum by(instance)(rate(state_store_range_scan_size_sum[1m]))/sum by(instance)(rate(state_store_range_scan_size_count[1m]))",
     "legendFormat": "range_scan (cn:{{instance}})"
    },
    {
     "expr": "sum by(instance)(rate(state_store_range_reverse_scan_size_sum[1m]))/sum by(instance)(rate(state_store_range_reverse_scan_size_count[1m]))",
     "legendFormat": "reverse_range_scan (cn:{{instance}})"
    }
   ]
  },
  {
   "title": "write ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_duration_count[1m])) by (instance)",
     "legendFormat": "write batch cn= {{instance}} "
    },
    {
     "expr": "sum(rate(state_store_shared_buffer_to_l0_duration_count[1m])) by (instance)",
     "legendFormat": "l0 cn = {{instance}} "
    }
   ]
  },
  {
   "title": "merge iterators ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_iter_merge_seek_duration_count[1m])) by (instance)",
     "legendFormat": "MI seek (cn:{{instance}})"
    },
    {
     "expr": "sum(rate(state_store_iter_merge_next_duration_count[1m])) by (instance)",
     "legendFormat": "MI next (cn:{{instance}})"
    }
   ]
  },
  {
   "title": "write duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_write_batch_duration_bucket[1m])) by (le, instance))",
     "legendFormat": "shared_buffer p50  (cn: {{instance}})"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_write_batch_duration_bucket[1m])) by (le, instance))",
     "legendFormat": "shared_buffer p90  (cn: {{instance}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_write_batch_duration_bucket[1m])) by (le, instance))",
     "legendFormat": "shared_buffer p99  (cn: {{instance}})"
    },
    {
     "expr": "sum by(le, instance)(rate(state_store_write_batch_duration_sum[1m]))  / sum by(le, instance)(rate(state_store_write_batch_duration_count[1m]))",
     "legendFormat": "shared_buffer avg (cn: {{instance}})"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_write_shared_buffer_sync_time_bucket[1m])) by (le, instance))",
     "legendFormat": "sync_remote p50 (cn: {{instance}})"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_write_shared_buffer_sync_time_bucket[1m])) by (le, instance))",
     "legendFormat": "sync_remote p90 (cn: {{instance}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_write_shared_buffer_sync_time_bucket[1m])) by (le, instance))",
     "legendFormat": "sync_remote p99 (cn: {{instance}})"
    },
    {
     "expr": "sum by(le, instance)(rate(state_store_write_shared_buffer_sync_time_sum[1m]))  / sum by(le, instance)(rate(state_store_write_shared_buffer_sync_time_count[1m]))",
     "legendFormat": "sync_remote avg (cn: {{instance}})"
    }
   ]
  },
  {
   "title": "merge iterators duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, instance) (rate(state_store_iter_merge_seek_duration_sum[1m])) / sum by(le, instance) (rate(state_store_iter_merge_seek_duration_count[1m]))",
     "legendFormat": "mi_seek avg (cn:{{instance}})"
    }
   ]
  },
  {
   "title": "build sstable duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, instance) (rate(state_store_shared_buffer_to_l0_duration_sum[1m])) / sum by(le, instance) (rate(state_store_shared_buffer_to_l0_duration_count[1m]))",
     "legendFormat": "avg (cn: {{instance}})"
    }
   ]
  },
  {
   "title": "write kv pair counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_tuple_counts[1m])) by (instance)",
     "legendFormat": "write_batch_kv_pair_count compute_node = {{instance}} "
    }
   ]
  },
  {
   "title": "row seq scan next duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, instance) (rate(batch_row_seq_scan_next_duration_sum[1m])) / sum by(le, instance) (rate(batch_row_seq_scan_next_duration_count[1m]))",
     "legendFormat": "row_seq_scan next avg (cn: {{instance}})"
    }
   ]
  },
  {
   "title": "write throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_size_sum[1m]))by(instance) / sum(rate(state_store_write_batch_size_count[1m]))by(instance)",
     "legendFormat": "shared_buffer (cn: {{instance}})"
    },
    {
     "expr": "sum(rate(state_store_shared_buffer_to_sstable_size_sum[1m]))by(instance) / sum(rate(state_store_shared_buffer_to_sstable_size_count[1m]))by(instance)",
     "legendFormat": "sync (cn: {{instance}})"
    }
   ]
  },
  {
   "title": "gRPC Hommock Table Comparision",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "get new TableID latency p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ GetNewTableId_p50"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_get_new_table_id_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance)) ",
       "legendFormat": "hummock_client_ GetNewTableId_p50 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "get new TableID latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ GetNewTableId_p90"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_get_new_table_id_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_ GetNewTableId_p90 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "get new TableID latency p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ GetNewTableId_p99"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_get_new_table_id_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_GetNewTableId_p99 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "add tables latency p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ AddTables_p50"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_add_tables_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_ AddTables_p50 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "add tables latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ AddTables_p90"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_add_tables_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_ AddTables_p90 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "add tables latency p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ AddTables_p99"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_add_tables_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_ AddTables_p99 compute_node = {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Hummock Compation Comparision",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true,
   "panels": [
    {
     "title": "get compation latency p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ GetCompactionTasks_p50"
      }
     ]
    },
    {
     "title": "get compation latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ GetCompactionTasks_p90"
      }
     ]
    },
    {
     "title": "get compation latency p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ GetCompactionTasks_p99"
      }
     ]
    },
    {
     "title": "report compation latency p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ ReportCompactionTasks_p50"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_report_compaction_task_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_ ReportCompactionTasks_p50 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "report compation latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ ReportCompactionTasks_p90"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_report_compaction_task_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_ ReportCompactionTasks_p90 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "report compation latency p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ ReportCompactionTasks_p99"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_report_compaction_task_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_ ReportCompactionTasks_p99 compute_node = {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Hommock Version Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "collapsed": true,
   "panels": [
    {
     "title": "pin version latency p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_manager_pinVersion_p50 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_pin_version_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_pinVersion_p50 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "pin version latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_manager_pinVersion_p90 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_pin_version_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_pinVersion_p90 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "pin version latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_manager_pinVersion_p99 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_pin_version_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_pinVersion_p99 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "unpin version latency p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_manager_unpinVersion_p50 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_unpinVersion_p50 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "unpin version latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_manager_unpinVersion_p90 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_unpin_version_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_unpinVersion_p90 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "unpin version latency p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_manager_unpinVersion_p99 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "hummock_client_unpinVersion_p99 compute_node = {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC meta: Catalog Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "collapsed": true,
   "panels": [
    {
     "title": "create latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[1m])) by (le))",
       "legendFormat": "Create_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[1m])) by (le))",
       "legendFormat": "Create_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[1m])) by (le))",
       "legendFormat": "Create_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[1m]))",
       "legendFormat": "Create_avg"
      }
     ]
    },
    {
     "title": "drop latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[1m])) by (le))",
       "legendFormat": "Drop_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[1m])) by (le))",
       "legendFormat": "Drop_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[1m])) by (le))",
       "legendFormat": "Drop_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[1m]))",
       "legendFormat": "Drop_avg"
      }
     ]
    },
    {
     "title": "get catalog latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[1m])) by (le))",
       "legendFormat": "GetCatalog_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[1m])) by (le))",
       "legendFormat": "GetCatalog_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[1m])) by (le))",
       "legendFormat": "GetCatalog_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[1m]))",
       "legendFormat": "GetCatalog_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC meta: Cluster Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "collapsed": true,
   "panels": [
    {
     "title": "add worker node latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[1m])) by (le))",
       "legendFormat": "AddWorkerNode_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[1m])) by (le))",
       "legendFormat": "AddWorkerNode_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[1m])) by (le))",
       "legendFormat": "AddWorkerNode_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[1m]))",
       "legendFormat": "AddWorkerNode_avg"
      }
     ]
    },
    {
     "title": "list all node latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[1m])) by (le))",
       "legendFormat": "ListAllNodes_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[1m])) by (le))",
       "legendFormat": "ListAllNodes_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[1m])) by (le))",
       "legendFormat": "ListAllNodes_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[1m]))",
       "legendFormat": "ListAllNodes_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC meta: Stream Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "collapsed": true,
   "panels": [
    {
     "title": "create materialized view latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m])) by (le))",
       "legendFormat": "CreateMaterializedView_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m])) by (le))",
       "legendFormat": "CreateMaterializedView_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m])) by (le))",
       "legendFormat": "CreateMaterializedView_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m]))",
       "legendFormat": "CreateMaterializedView_avg"
      }
     ]
    },
    {
     "title": "drop materialized view latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m])) by (le))",
       "legendFormat": "DropMaterializedView_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m])) by (le))",
       "legendFormat": "DropMaterializedView_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m])) by (le))",
       "legendFormat": "DropMaterializedView_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m]))",
       "legendFormat": "DropMaterializedView_avg"
      }
     ]
    },
    {
     "title": "flush latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[1m])) by (le))",
       "legendFormat": "Flush_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[1m])) by (le))",
       "legendFormat": "Flush_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[1m])) by (le))",
       "legendFormat": "Flush_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[1m]))",
       "legendFormat": "Flush_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC meta: Hummock Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 },
   "collapsed": true,
   "panels": [
    {
     "title": "version latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le))",
       "legendFormat": "UnpinVersion_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le))",
       "legendFormat": "UnpinVersion_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le))",
       "legendFormat": "UnpinVersion_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m]))",
       "legendFormat": "UnpinVersion_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le))",
       "legendFormat": "PinVersion_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le))",
       "legendFormat": "PinVersion_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le))",
       "legendFormat": "PinVersion_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m]))",
       "legendFormat": "PinVersion_avg"
      }
     ]
    },
    {
     "title": "snapshot latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) by (le))",
       "legendFormat": "UnpinSnapshot_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) by (le))",
       "legendFormat": "UnpinSnapshot_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) by (le))",
       "legendFormat": "UnpinSnapshot_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m]))",
       "legendFormat": "UnpinSnapshot_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m])) by (le))",
       "legendFormat": "PinSnapshot_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m])) by (le))",
       "legendFormat": "PinSnapshot_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m])) by (le))",
       "legendFormat": "PinSnapshot_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m]))",
       "legendFormat": "PinSnapshot_avg"
      }
     ]
    },
    {
     "title": "compation latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "GetCompactionTasks_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le))",
       "legendFormat": "GetCompactionTasks_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le))",
       "legendFormat": "GetCompactionTasks_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m]))",
       "legendFormat": "GetCompactionTasks_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "ReportCompactionTasks_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "ReportCompactionTasks_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "ReportCompactionTasks_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m]))",
       "legendFormat": "ReportCompactionTasks_avg"
      }
     ]
    },
    {
     "title": "table latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "AddTables_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "AddTables_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "AddTables_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m]))",
       "legendFormat": "AddTables_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "GetNewTableId_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "GetNewTableId_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "GetNewTableId_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) / sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m]))",
       "legendFormat": "GetNewTableId_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC: hummock meta client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 },
   "collapsed": true,
   "panels": [
    {
     "title": "compaction_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(state_store_report_compaction_task_counts{instance =~\"$compute_node\"}[1m])) by(instance)",
       "legendFormat": "report_compaction_task_counts compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "version_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_pin_version_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "pin_version_latency_p50 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_pin_version_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "pin_version_latency_p99 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_pin_version_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "pin_version_latencyp90 compute_node = {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_pin_version_latency_sum{instance =~\"$compute_node\"}[1m])) / sum(irate(state_store_pin_version_latency_count{instance =~\"$compute_node\"}[1m]))",
       "legendFormat": "pin_version_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "unpin_version_latency_p50 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "unpin_version_latency_p99 compute_node = {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_version_latency_sum{instance =~\"$compute_node\"}[1m])) / sum(irate(state_store_unpin_version_latency_count{instance =~\"$compute_node\"}[1m]))",
       "legendFormat": "unpin_version_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_unpin_version_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "unpin_version_latency_p90 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "version_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(state_store_pin_version_counts{instance =~\"$compute_node\"}[1m])) by(instance)",
       "legendFormat": "pin_version_counts compute_node = {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_version_counts{instance =~\"$compute_node\"}[1m])) by(instance)",
       "legendFormat": "unpin_version_counts compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "snapshot_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_pin_snapshot_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "pin_snapshot_latency_p50 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_pin_snapshot_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "pin_snapshot_latency_p99 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_pin_snapshot_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "pin_snapshot_latencyp90 compute_node = {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_pin_snapshot_latency_sum[1m])) / sum(irate(state_store_pin_snapshot_latency_count[1m]))",
       "legendFormat": "pin_snapshot_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_snapshot_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "unpin_snapshot_latency_p50 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_snapshot_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "unpin_snapshot_latency_p99 compute_node = {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_snapshot_latency_sum[1m])) / sum(irate(state_store_unpin_snapshot_latency_count[1m]))",
       "legendFormat": "unpin_snapshot_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_unpin_snapshot_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "unpin_snapshot_latency_p90 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "snapshot_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(state_store_pin_snapshot_counts{instance =~\"$compute_node\"}[1m])) by(instance)",
       "legendFormat": "pin_snapshot_counts compute_node = {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_snapshot_counts{instance =~\"$compute_node\"}[1m])) by(instance)",
       "legendFormat": "unpin_snapshot_counts compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "table_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_add_tables_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le,instance))",
       "legendFormat": "pin_snapshot_latency_p50 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_add_tables_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "add_table_latency_p99 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_add_tables_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "add_table_latency_p90 compute_node = {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_add_tables_latency_sum[1m])) / sum(irate(state_store_add_tables_latency_count[1m]))",
       "legendFormat": "add_table_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_get_new_table_id_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "get_new_table_id_latency_p50 compute_node = {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_get_new_table_id_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "get_new_table_id_latency_p99 compute_node = {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_get_new_table_id_latency_sum[1m])) / sum(irate(state_store_get_new_table_id_latency_count[1m]))",
       "legendFormat": "get_new_table_id_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_get_new_table_id_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "get_new_table_id_latency_p90 compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "table_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum(irate(state_store_add_tables_counts{instance =~\"$compute_node\"}[1m]))by(instance)",
       "legendFormat": "add_tables_counts compute_node = {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_get_new_table_id_counts{instance =~\"$compute_node\"}[1m]))by(instance)",
       "legendFormat": "get_new_table_id_counts compute_node = {{instance}} "
      }
     ]
    },
    {
     "title": "compation_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_report_compaction_task_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "report_compaction_task_latency_p50 compute_node = {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_report_compaction_task_latency_bucket{instance =~\"$compute_node\"}[1m])) by (le, instance))",
       "legendFormat": "report_compaction_task_latency_p99 compute_node = {{instance}}"
      },
      {
       "expr": "sum(irate(state_store_report_compaction_task_latency_sum[1m])) / sum(irate(state_store_report_compaction_task_latency_count[1m]))",
       "legendFormat": "report_compaction_task_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, instance))",
       "legendFormat": "report_compaction_task_latency_p90 compute_node = {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}